// Vue/src/orig_App.vue
<template>
  <DxDataGrid 
    :data-source="employees"
    @editor-preparing="onEditorPreparing">
    <DxEditing
      :allow-updating="true"
      :allow-adding="true" />

    <DxColumn
      caption="Name"
      data-field="CustomerID"
      :set-cell-value="setCellValue">
      <DxLookup 
        :data-source="customers"
        value-expr="CustomerID"
        display-expr="CustomerName" />
    </DxColumn>
    <DxColumn data-field="Address" />
    <DxColumn data-field="Phone" />
  </DxDataGrid>
</template>

<script>
import DxDataGrid, {
  DxEditing,
  DxColumn,
  DxLookup,
} from "devextreme-vue/data-grid";
import { customers, employees } from "./data";

export default {
  name: "App",
  components: {
    DxDataGrid,
    DxEditing,
    DxColumn,
    DxLookup,
  },
  data() {
    return {
      customers: customers,
      employees: employees
    };
  },
  methods: {
    onEditorPreparing(e) {
      if (e.parentType === "dataRow" && e.dataField === "CustomerID") {
        e.editorOptions.onValueChanged = function (ev) {
          let selectedItem = ev.component.option("selectedItem");
          e.setValue(selectedItem);
        };
      }
    },
    setCellValue(rowData, value) {
      rowData.CustomerID = value.CustomerID;
      rowData.Address = value.Address;
      rowData.Phone = value.Phone;
    },
  },
};
</script>

<style>
</style>

// React/src/orig_App.js
import React from "react";
import './App.css';
import 'devextreme/dist/css/dx.common.css';
import 'devextreme/dist/css/dx.light.css';

import DataGrid, { Editing, Column, Lookup } from "devextreme-react/data-grid";
import { customers, employees } from "./data";

function App(props) {
  function onEditorPreparing(e) {
    if (e.parentType === "dataRow" && e.dataField === "CustomerID") {
      e.editorOptions.onValueChanged = function (ev) {
        let selectedItem = ev.component.option("selectedItem");
        e.setValue(selectedItem);
      };
    }
  }

  function setCellValue(rowData, value) {
    rowData.CustomerID = value.CustomerID;
    rowData.Address = value.Address;
    rowData.Phone = value.Phone;
  }

  return (
    <div>
      <DataGrid
        dataSource={employees}
        onEditorPreparing={onEditorPreparing}>
          <Editing 
            allowUpdating={true}
            allowAdding={true} />

          <Column
            caption="Name"
            dataField="CustomerID"
            setCellValue={setCellValue}>
            <Lookup
              dataSource={customers}
              valueExpr="CustomerID"
              displayExpr="CustomerName" />
          </Column>
          <Column dataField="Address" />
          <Column dataField="Phone" />
      </DataGrid>
    </div>
  );
}

export default App;
