// React/src/orig_App.js
import React from "react";
import './App.css';
import 'devextreme/dist/css/dx.common.css';
import 'devextreme/dist/css/dx.light.css';

import DataGrid, { Editing, Column, Lookup } from "devextreme-react/data-grid";
import { customers, employees } from "./data";

function App(props) {
  function onEditorPreparing(e) {
    if (e.parentType === "dataRow" && e.dataField === "CustomerID") {
      e.editorOptions.onValueChanged = function (ev) {
        let selectedItem = ev.component.option("selectedItem");
        e.setValue(selectedItem);
      };
    }
  }

  function setCellValue(rowData, value) {
    rowData.CustomerID = value.CustomerID;
    rowData.Address = value.Address;
    rowData.Phone = value.Phone;
  }

  return (
    <div>
      <DataGrid
        dataSource={employees}
        onEditorPreparing={onEditorPreparing}>
          <Editing 
            allowUpdating={true}
            allowAdding={true} />

          <Column
            caption="Name"
            dataField="CustomerID"
            setCellValue={setCellValue}>
            <Lookup
              dataSource={customers}
              valueExpr="CustomerID"
              displayExpr="CustomerName" />
          </Column>
          <Column dataField="Address" />
          <Column dataField="Phone" />
      </DataGrid>
    </div>
  );
}

export default App;

// Angular/src/app/orig_app.component.ts
import { Component } from '@angular/core';
import { Employee, Customer, Service } from "./app.service";
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
  providers: [Service]
})
export class AppComponent {
  employees: Employee[];
  customers: Customer[];
  constructor(service: Service) {
    this.employees = service.getEmployees();
    this.customers = service.getCustomers();
  }

  onEditorPreparing = (e) => {
    if (e.parentType === "dataRow" && e.dataField === "CustomerID") {
      e.editorOptions.onValueChanged = function (ev) {
        let selectedItem = ev.component.option("selectedItem");
        e.setValue(selectedItem);
      };
    }
  };

  setCellValue = (rowData, value) => {
    rowData.CustomerID = value.CustomerID;
    rowData.Address = value.Address;
    rowData.Phone = value.Phone;
  };
}

<dx-data-grid
    id="gridContainer"
    [dataSource]="employees"
    (onEditorPreparing)="onEditorPreparing($event)"
    >
    
    <dxo-editing [allowUpdating]="true" [allowAdding]="true"></dxo-editing>
    
    <dxi-column
    	caption="Name"
       	dataField="CustomerID"
        [setCellValue]="setCellValue"
    >
        <dxo-lookup
        	[dataSource]="customers"
         	valueExpr="CustomerID"
            displayExpr="CustomerName"
        >
        </dxo-lookup>
    </dxi-column>
    
    <dxi-column dataField="Address"></dxi-column>
    <dxi-column dataField="Phone"></dxi-column>
    
</dx-data-grid>
